name: Build Android APK

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

      - name: Clonar repositorio
        uses: actions/checkout@v4

      - name: Instalar Node
        uses: actions/setup-node@v4
        with:
          node-version: "22"

      - name: Instalar dependencias
        run: |
          rm -f package-lock.json
          npm install --legacy-peer-deps

      - name: Construir proyecto
        run: |
          npm run build
          ls -la
          ls -la .output || true
          ls -la .output/public || true

      - name: Instalar Android Capacitor
        run: |
          npm install @capacitor/android --legacy-peer-deps

      - name: Crear Android
        run: |
          npx cap add android || true

      - name: Copiar archivos web
        run: |
          npx cap copy

      - name: Sincronizar Capacitor
        run: |
          npx cap sync

      - name: Configurar Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "21"

      - name: Permisos Gradle
        run: chmod +x android/gradlew

      - name: Compilar APK
        run: |
          cd android
          ./gradlew assembleDebug

      - name: Subir APK
        uses: actions/upload-artifact@v4
        with:
          name: app-debug
          path: android/app/build/outputs/apk/debug/*.apk
